name: C/C++ CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: docker://devkitpro/devkita64:latest
    - name: make
      run: make LATESTTAG=Beta

    - name: Upload Release
      uses: Genwald/create-release@eba889c
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: beta
        code: beta
        body: Latest commit, automatically updated. May not be fully tested or fully working.
        prerelease: true
        recreate: true
        assets: Ultimate_Mod_Manager.nro:Ultimate_Mod_Manager.nro:application/octet-stream
